name: Scheduled Tests

on:
  schedule:
    - cron: "14 14 * * *"

jobs:
  linux-tests:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python $ # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -e '.[testing]' --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Test with pytest
        run: python -m pytest -n=auto test/
